import tat1 from './realTatto1.jpeg'
import tat2 from './realTatto2.jpeg'
import tat3 from './realTatto3.jpeg'
import tat4 from './realTatto4.jpeg'
import tat5 from './tatto2.jpg'
import tat6 from './tatto3.jpg'
import fb from './facebook.png'
import gp from './gplogo.png'
import ig from './iglogo.png'
import insta from './instagram.png'
import ms from './mslogo.png'
import out from './outlook.png'
import msl from './msoutlook.svg'

export {tat1, tat2, tat3, tat4, tat5, tat6, fb, gp, ig, insta, ms, out, msl}